language: ruby
jdk:
  - openjdk8
rvm:
  - 2.7.2
install:
  - rvm install ruby-2.7.2
  - rvm use 2.7.2
  - bundle install
git:
  depth: 10
env:
  global:
    - JRUBY_OPTS="-J-Xmx700M"
    - JAVA_OPTS="-Xmx700m"
script: bundle exec rake ci
